(ns basics.vector)
(println (vector 1 2 3 4 5 6))
(println (def the-vector [1 2 3 4 5 6]))
(println the-vector)
(println (get the-vector 0))
(println (get the-vector 2))
(println (get the-vector 20))
(println (assoc the-vector 2 20))
(println the-vector)
(println (assoc the-vector 6 20))
(println (conj [1 2 3 4 5] 6))
(println (conj (list 1 2 3 4 5) 6))
(print "peek: ")
(println (peek [1 2]))
(print "pop: ")
(println (pop [1 2]))
(println "(the-vector 3): " (the-vector 3))