/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.poc.pgradle.vertx.app;

import io.vertx.core.AbstractVerticle;

public class MainVerticle extends AbstractVerticle {

    @Override
    public void start() {
        vertx.createHttpServer()
                .requestHandler(req -> req.response().end("Hello Vert.x!"))
                .listen(8080);

        System.out.println("http://localhost:8080");
    }

}