/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

val vertxVersion = "3.9.4"

dependencies {
    implementation(platform("io.vertx:vertx-stack-depchain:$vertxVersion"))

    implementation("io.vertx:vertx-core")
}
