/*
 * Copyright (c) 2021. StulSoft
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.poc.pgradle.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
