/*
 * Copyright (c) 2022, StulSoft
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.poc;

public class App {
    public static void main(String[] args){
     test1();
    }
    private static void test1(){
        System.out.println("==>test1");
        TestDTO testDTO = new TestDTO("name 1", 123);
        System.out.println(testDTO);
        var age = testDTO.getAge();
        var name=testDTO.getName();
    }
}
