/*
 * Copyright (c) 2022, StulSoft
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.poc;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class App {
    public static void main(String[] args){
     test1();
    }
    private static void test1(){
        log.info("==>test1");
        TestDTO testDTO = new TestDTO("name 1", 123);
        log.info("testDTO: {}", testDTO);
    }
}
