/*
 * Copyright (c) 2021. StulSoft
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.poc.pgradle.app;

import com.stulsoft.poc.pgradle.app.MessageUtils;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class MessageUtilsTest {
    @Test public void testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
