/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.poc.pjunit5;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @BeforeAll
    public static void init() {
        System.out.println("==init");
    }

    @BeforeEach
    public void initForEach(){
        System.out.println("==initForEach");
    }

    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
