/*
 * Copyright (c) 2021. StulSoft
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.poc.websocket.ex1;

import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Random;

public class AppClient2 {
    private static final Logger logger = LoggerFactory.getLogger(AppClient2.class);

    public static void main(String[] args) {
        logger.info("==>main");
        var vertx = Vertx.vertx();
        vertx.deployVerticle(
                new WebSocketClient2Verticle(),
                new DeploymentOptions()
                        .setConfig(new JsonObject()
                                .put("user", "user " + new Random().nextInt(1000))));
    }
}
